# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{simpleton}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Vladimir Andrijevik"]
  s.date = %q{2010-03-06}
  s.description = %q{Simpleton takes a simple, object-oriented approach to the way
you deploy your server applications.

With Simpleton, you express (and test) the things that need to
happen during a deployment as Middleware objects. A Command Runner
runs the command from a Middleware on a remote host, and
Simpleton orchestrates the operation of Command Runners on the
hosts you've configured.

Simpleton ships with a few common Middleware, a couple of Command
Runners, and makes it very easy to roll your own. Enjoy!
}
  s.email = %q{vladimir+simpleton@andrijevik.net}
  s.files = [
    "Rakefile",
     "lib/simpleton.rb",
     "lib/simpleton/command_runners.rb",
     "lib/simpleton/command_runners/system.rb",
     "lib/simpleton/middleware.rb",
     "lib/simpleton/middleware/git_bootstrapper.rb",
     "lib/simpleton/worker.rb",
     "test/command_runners/system_test.rb",
     "test/middleware/git_bootstrapper_test.rb",
     "test/simpleton_test.rb",
     "test/test_helper.rb",
     "test/worker_test.rb"
  ]
  s.homepage = %q{http://github.com/vandrijevik/simpleton}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Simpleton makes deploying server apps simple.}
  s.test_files = [
    "test/command_runners/system_test.rb",
     "test/middleware/git_bootstrapper_test.rb",
     "test/simpleton_test.rb",
     "test/test_helper.rb",
     "test/worker_test.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

